const DataDemo = {
  USER: [
    {
      id: 1,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 1,
      active: true,
    },
    {
      id: 2,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 2,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 2,
      active: true,
    },
    {
      id: 3,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 3,
      active: false,
    },
    {
      id: 4,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 1,
      active: true,
    },
    {
      id: 5,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 2,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 2,
      active: false,
    },
    {
      id: 6,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 3,
      active: true,
    },
    {
      id: 7,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 2,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 1,
      active: true,
    },
    {
      id: 8,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 2,
      active: false,
    },
    {
      id: 9,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 3,
      active: false,
    },
    {
      id: 10,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 1,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 1,
      active: true,
    },
    {
      id: 11,
      avatar: "https://avatars0.githubusercontent.com/u/7895451?s=460&v=4",
      name: "Elena Richards",
      email: "ElenaRichards@gmail.com",
      phone: "0939373239",
      gender: 2,
      class: "Grade 1",
      dateOfBirth: "1993/10/18",
      type: 2,
      active: true,
    },
  ],
  FILES: [
    {
      id: "1",
      name: "Work Documents",
      type: "folder",
      owner: "me",
      size: "",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Work Documents",
      offline: true,
    },
    {
      id: "2",
      name: "Public Documents",
      type: "folder",
      owner: "public",
      size: "",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Public Documents",
      offline: true,
    },
    {
      id: "3",
      name: "Private Documents",
      type: "folder",
      owner: "me",
      size: "",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Private Documents",
      offline: true,
    },
    {
      id: "4",
      name: "Ongoing projects",
      type: "document",
      owner: "Emily Bennett",
      size: "1.2 Mb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Ongoing projects",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "5",
      name: "Shopping list",
      type: "document",
      owner: "Emily Bennett",
      size: "980 Kb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Shopping list",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "6",
      name: "Invoices",
      type: "spreadsheet",
      owner: "Emily Bennett",
      size: "750 Kb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Invoices",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "7",
      name: "Crash logs",
      type: "document",
      owner: "Emily Bennett",
      size: "980 Mb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Crash logs",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "8",
      name: "System logs",
      type: "document",
      owner: "Emily Bennett",
      size: "52 Kb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > System logs",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "9",
      name: "Prices",
      type: "spreadsheet",
      owner: "Emily Bennett",
      size: "27 Mb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Prices",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "10",
      name: "Anabelle Manual",
      type: "document",
      owner: "Emily Bennett",
      size: "1.1 Kb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Anabelle Manual",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
    {
      id: "11",
      name: "Steam summer sale budget",
      type: "spreadsheet",
      owner: "Emily Bennett",
      size: "505 Kb",
      modified: "July 8, 2017",
      opened: "July 8, 2017",
      created: "July 8, 2017",
      extention: "",
      location: "My Files > Documents > Steam summer sale budget",
      offline: true,
      preview: "assets/images/etc/sample-file-preview.jpg",
    },
  ],
};

export default DataDemo;
