/* LIBRARY */
const Language = {
  vi: {
  },
  en: {
    connect_wallet: "Connect Wallet",
    our_advandtages: "OUR ADVANDTAGES",



    apply: "Áp dụng",
    all: "Tất cả",
    cancel: "Hủy bỏ",
    ok: "OK",
    save: "Lưu",
    add: "Thêm",
    edit: "Sửa",
    delete: "Xóa",
    read: "Đọc",
    close: "Đóng",
    other: "Khác",
    fisrt_page: "Trang đầu",
    next_page: "Trang kế",
    prev_page: "Trang trước",
    last_page: "Trang cuối",
    des_drag_and_drop: "Kéo và thả tệp hoặc nhấn vào đây để tải lên",
    selected_files: "Tệp tin đã chọn",
    files: "Tệp tin",
    welcome_back: "Chào mừng bạn đến với FourHoursemen",
    network_error: "Lỗi kết nối",
    des_empty_user: "Chưa có người dùng nào",
    des_add_user_success: "Thêm người dùng thành công",
    des_add_user_failed: "Thêm người dùng thất bại",
    my_profile: "Thông tin cá nhân",
    logout: "Đăng xuất",
    row_per_page: "Số item hiển thị",
    of: "của",
    rows_user: "người dùng",
    send: "Gửi",
    go_back: "Trở lại",
    error: "Lỗi",

    admin: "Quản trị",
    teacher: "Người dùng 1",
    student: "Người dùng 2",
    user_management: "Người Dùng",
    username: "Tên đăng nhập",
    role: "Quyền",
    password: "Mật khẩu",
    confirm_password: "Nhập lại mật khẩu",
    new_user: "Tạo tài khoản",
    edit_user: "Sửa thông tin",
    delete_user: "Xóa người dùng",
    des_delete_user_multi_1: "Bạn muốn xóa",
    des_delete_user_multi_2: "người dùng ",
    des_delete_user: "Bạn muốn xóa người dùng ",
    des_choose_role: "Chọn quyền cho người dùng",
    des_error_fill_input: "Vui lòng nhập thông tin bắt buộc",
    des_error_min_length: "Mật Khẩu tối thiểu 6 kí tự",
    des_error_email_format: "Định dạng e-mail không chính xác",
    des_error_phone_format: "Định dạng số điện thoại không chính xác",
    des_error_confpass_not_like: "Bạn nhập lại mật khẩu không chính xác",

    des_delete_test_multi_1: "Bạn muốn xóa",

    account: "Tài khoản",
    change_password: "Đổi mật khẩu",
    full_name: "Họ và Tên",
    first_name: "Họ",
    last_name: "Tên",
    date_of_birth: "Ngày sinh",
    gender: "Giới tính",
    home_address: "Địa chỉ",
    phone: "Số điện thoại",
    school: "Trường",
    male: "Nam",
    female: "Nữ",
    new_password: "Mật khẩu mới",
    confirm_new_password: "Nhập lại mật khẩu mới",

    public: "Công khai",
    private: "Riêng tư",
    active: "Hoạt Động",
    inactive: "Ngưng Hoạt Động",
    draft: "Nháp",

    status: "Trạng thái",
    random: "Random",
    information: "Thông tin",
    content: "Nội dung",
    attach_file_video_audio: "Đính kèm file video/audio",
    setting: "Thiết lập",
    infor: "Thông tin cơ bản",

    user: "Người Dùng",
    available_offline: "Đã tải xuống",
    info: "Thông tin",
    create: "Tạo",

    username_email: "Tên đăng nhập/E-mail",
    login: "Đăng nhập",
    register: "Đăng ký",
    forgot_password: "Quên mật khẩu",
    need_an_account: "Bạn muốn đăng ký tài khoản?",
    charater: "ký tự",
    des_error_min: "Cần nhập ít nhất là",
    des_show_password: "Bấm để xem mật khẩu",
    des_error_email_password:
      "Tên đăng nhập/E-mail hoặc mật khẩu không chính xác",
    des_error_send_forgot_password:
      "E-mail chưa được đăng ký, vui lòng nhập lại.",
    des_error_token_expired:
      "Phiên làm việc của bạn đã hết, vui lòng đăng nhập lại.",
    des_user_not_found: "Người dùng đang tồn tại",

    des_upload_file_success: "Tải lên thành công",
    des_upload_file_failed: "Tải lên thất bại",
    des_edit_user_success: "Sửa thông tin thành công",
    des_edit_user_failed: "Sửa thông tin thất bại",
    des_change_password_user_success: "Đổi mật khẩu thành công",
    des_change_password_user_failed: "Đổi mật khẩu thất bại",
    des_trash_user_success: "Xóa người dùng thành công",
    des_trash_user_failed: "Xóa người dùng thất bại",
    des_trash_user_invalid: "Không thể xóa người dùng này",

    title: "Tiêu đề",
    title_placeholder: "Nhập tiêu đề",
    description: "Nội dung",
    description_placeholder: "Nhập nội dung",
    date_created: "Ngày tạo",

    des_password_input_error: "Vui lòng nhập mật khẩu",
    des_row_selected: "dòng đã chọn",
    sorry_but_we_could_not_find_the_page_you_are_looking_for: "Xin lỗi nhưng chúng tôi không thể tìm thấy trang bạn đang tìm",
    des_trash_per_success: "Xóa quyền thành công",
    des_trash_per_failed: "Xóa quyền thất bại",
    management: "Quản lý",

    change_status: "Đổi trạng thái",
    des_change_status_success: "Chuyển trạng thái người dùng thành công",
    des_change_status_failed: "Chuyển trạng thái người dùng thất bại",

    add_user: "Thêm người dùng",
    url: "Đường dẫn",
    object: "Đối Tượng",
    permission: "Phân Quyền",
    edit_permission: "Sửa Phân Quyền",
    no: "Không",
    new_permission: "Tạo Quyền Mới",
    misson: "Quyền",

    home: "Trang Chủ",
    practice: "Luyện Tập",
    news: "Tin Tức",
    login: "Đăng Nhập",
    signup: "Đăng Kí",
    more: "Xem thêm",
    gifted_sub: "Năng Khiếu",
    address_cty: "TPHCM",
    phone_cty: "0348010604",
    phone_table_cty: "0348010604",
    email_cty: "fourhoursemen@gmail.com",
    copy_right: "2021 Copyright by FourHorsemen",
    keep: "Đang diễn ra",
    go_detail: "Xem Chi Tiết",
    see_suggest: "Xem gợi ý",
    suggest: "Gợi ý",
    or: "hoặc",
    login_with_google: "Đăng nhập với Google",
    login_with_facebook: "Đăng nhập với Facebook",
    register_with_google: "Đăng ký với Google",
    register_with_facebook: "Đăng ký với Facebook",
    already_have_account: "Đã có tài khoản?",
    dont_have_account: "Chưa có tài khoản?",
    email: "E-mail",
    txt_login_social: "Vui lòng điền các thông tin còn thiếu để hoàn tất việc đăng ký.",
    confirm: "Xác nhận",
    search: "Tìm kiếm",

    finished: "Đã kết thúc",
    back: "Quay lại",

    error_password: "Mật khẩu không chính xác",
    placeholder_choise_question: "Chọn từ đúng",
    placeholder_answer_question: "Chọn câu đúng",
    des_have_error: "Có lỗi xảy ra",
 
    server_error: "Lỗi máy chủ! Vui lòng thử lại sau!",
    share: "Chia sẻ",
    update: "Cập nhập",
    update_profile: "Cập nhập hồ sơ",
    txt_update_profile: "Cập nhập hồ sơ của bạn để hoàn tất việc đăng ký",
    skip: "Bỏ qua"
  }
};

export default Language;
