/* LIBRARY */
const Success = {
  // TEST success state
  EDIT_TEST_QUESTION_SUCCESS: "EDIT_TEST_QUESTION_SUCCESS",
  EDIT_SCORE_QUESTION_TEST_SUCCESS: "EDIT_SCORE_QUESTION_TEST_SUCCESS",
  TRASH_QUESTION_TEST_SUCCESS: "TRASH_QUESTION_TEST_SUCCESS"
};

export default Success;
